//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int AnimalId { get; set; }
        public string Name { get; set; }
        public int Weight { get; set; }
        public string Gender { get; set; }
        public string PreferenceInFood { get; set; }
    }
}
