//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistType
    {
        public int ArtistTypeId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Type { get; set; }
        public string Perfomance { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
